### ISSUE TITLE
Files to import into EEDA/propose changes to integrate into ESPHome?

### ISSUE THREAD

**Issue by Johncunningham918** [DustinWatts/ESP32_TFT_Combiner#2]
This board has also been being utilized to easily integrate the ili9xxx/xpt2046 components into ESPHome, but a change to the touchscreen component in ESPHome has broken this PCB design. 

The new config in ESPHome requires two SPI buses; one for the display and one for the touchscreen rather than one SPI bus sharing the pins for the xpt2046 and the ili9xxx display. Is it possible to obtain the files to import the pcb into EEDA to modify it to accommodate these changes to continue using it within ESPhome?

**Comment by DustinWatts** [comment]
Hi @Johncunningham918 It is a shared project on EasyEDA. I just never got around to post the link here on Github. But this should do it: 

https://oshwlab.com/DustinWatts/ftd-plugin-board

**Comment by DustinWatts** [comment]
Edited the README.md with the link to the shared project. https://github.com/DustinWatts/ESP32_TFT_Combiner/commit/6304fc26156269e2a9c7af9ad3d7695b7c24f728

**Comment by Johncunningham918** [comment]
Thank you very much, Dustin! Many people will appreciate your willingness to share the design!
